##
# This file is part of the ChillDev FileManager bundle.
#
# @author Rafal Wrzeszcz <rafal.wrzeszcz@wrzasq.pl>
# @copyright 2013 © by Rafal Wrzeszcz - Wrzasq.pl.
# @version 0.1.1
# @since 0.1.1
# @package ChillDev\Bundle\FileManagerBundle
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

service_name: "travis-ci"
src_dir: "."
coverage_clover: "Resources/doc/coverage/clover.xml"
json_path: "Resources/doc/coverage/coveralls-upload.json"
