##
# This file is part of the ChillDev FileManager bundle.
#
# @author Rafal Wrzeszcz <rafal.wrzeszcz@wrzasq.pl>
# @copyright 2012 - 2014 © by Rafal Wrzeszcz - Wrzasq.pl.
# @version 0.1.4
# @since 0.0.1
# @package ChillDev\Bundle\FileManagerBundle
##

#FIXME: https://github.com/travis-ci/travis-ci/issues/753

language: "php"

php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"

env:
    - "SYMFONY_VERSION=2.2.*"
    - "SYMFONY_VERSION=2.3.*"
    - "SYMFONY_VERSION=2.4.*"
    - "SYMFONY_VERSION=2.5.*"

before_script:
    - "composer self-update"
    - "composer --dev --no-progress require symfony/symfony:${SYMFONY_VERSION}"
    - "composer --dev --no-progress --optimize-autoloader install"

script: "make ci"

after_script: "make coveralls"
